// Generates src/demux/DemuxerWorkerInline.ts from DemuxerWorker.ts.
//
// The DemuxerWorker runs as a Blob Worker with no external file dependency, so
// its bundled+minified source is embedded as a string constant. That generated
// file is git-ignored; this script regenerates it on tsup build, `pretest` and
// `pretypecheck`, so a fresh checkout always has it before anything imports it.
import esbuild from 'esbuild';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.join(__dirname, '..');

export function inlineWorker() {
  const workerSrc = path.join(pkgRoot, 'src/demux/DemuxerWorker.ts');
  const workerDest = path.join(pkgRoot, 'src/demux/DemuxerWorkerInline.ts');

  const result = esbuild.buildSync({
    entryPoints: [workerSrc],
    bundle: true,
    minify: true,
    write: false,
    target: 'es2022',
    format: 'iife',
  });

  const code = result.outputFiles[0].text;

  fs.writeFileSync(
    workerDest,
    `// Auto-generated by scripts/inline-worker.mjs — do not edit. Git-ignored;\n` +
    `// regenerated on tsup build, pretest and pretypecheck.\n` +
    `export const DEMUXER_WORKER_SOURCE = ${JSON.stringify(code)};\n`
  );
  console.log('[inline-worker] src/demux/DemuxerWorkerInline.ts generated.');
}

// Allow running directly: `node scripts/inline-worker.mjs`
if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  inlineWorker();
}
